### ISSUE TITLE
Optimization of precipitation

### ISSUE THREAD

**Issue by Ainazik23** [my-name-is-samael/BeamJoy#27] opened 2024-12-02 19:12 UTC
Precipitation such as snow and rain loads the computer very much, I would like you to optimize this process, I will be very glad if you implement it

**Comment by my-name-is-samael** [comment] 2024-12-02 19:37
Unfortunately, the issue is caused by the game itself. You can reproduce it in solo freeroam on West Coast, for instance, in the world editor (F11), you can play with the precipitation values and see it causes massive fps drops :(

Eventually we will get an update to enhanced weather effects (and textures grip 🤞 )

**Comment by my-name-is-samael** [comment] 2024-12-02 20:29
Will be in the 1.1.2
For it to work, you will have to remove your `Resources/Server/BeamJoyData/db/maps.json` file

**Closed** 2024-12-04 11:19 UTC
Labels: wontfix
